<a href="https://colab.research.google.com/github/JothilakshmiAnand/AutomationCICD/blob/main/NumpyExamples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


In [3]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print (a+b)

[5 7 9]


In [7]:
arr2d = np.array([[1, 2, 3],
                 [4, 5, 6]])
print(arr2d)

[[1 2 3]
 [4 5 6]]


In [8]:
np.zeros((2,3))


array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.arange(0,12,2)

array([ 0,  2,  4,  6,  8, 10])

In [18]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [26]:
arr = np.array([[1,2,3],
                [4,5,6]])

print(arr.dtype)

int64


In [30]:
arr1 = np.array([10,34,65,98,100])
print(arr1[1:4])

[34 65 98]


In [37]:
arr2d = np.array([[10,20,30],
                  [40,50,60]])
print(arr2d[0,:])

[10 20 30]


In [43]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a ** b)

[  1  32 729]


In [52]:
arr = np.array([34,10,65,23,98,100])
print(np.min((arr)))

10


In [59]:
a = np.array([[1,2],
              [3,4]])
b = np.array([[5,6],
              [7,8]])

print(np.linalg.det(a))

-2.0000000000000004


In [4]:
arr = np.array([10,20,30,40,50])
print(arr[arr>25])

[30 40 50]


In [9]:
arr = np.arange(1,9)
#print(arr.reshape(2,4))
print(arr.flatten())

[1 2 3 4 5 6 7 8]


In [18]:
#print(np.random.rand(2,3) )
print(np.random.randint(1,10,5))
np.random.seed(42)

[9 1 3 7 4]


In [20]:
arr = np.array([10, np.nan, 20, 30, np.nan])
print(np.isnan(arr))      # identify NaN
print(arr[~np.isnan(arr)]) # remove NaN → [10. 20. 30.]

[False  True False False  True]
[10. 20. 30.]
